# Example: How to use this reusable workflow in your repository
# Save this as .github/workflows/agent-preview.yml in your repo

name: AI Agent Preview Deploy

on:
  push:
    branches:
      - "claude/**"
      - "gemini/**"
      - "copilot/**"
      - "jules/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGE_TOKEN }}

      - name: Build app
        run: npm run build

      - name: Clean build artifacts
        run: |
          # Remove Windows Zone.Identifier files that cause upload issues
          find dist/ build/ out/ -name "*.Zone.Identifier" -delete 2>/dev/null || true
          find dist/ build/ out/ -name "*:*" -delete 2>/dev/null || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            build/
            out/
          retention-days: 1

  deploy-preview:
    needs: build
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    uses: Stefan-Landvogt-IT-Consulting/firebase-agent-preview-deploy/.github/workflows/agent-preview-deploy.yml@main
    with:
      firebase_project: "my-project-dev"
      # For single-app repos (uncomment if needed):
      # default_app: 'web'
      # default_target: 'web'
      # For multi-app repos with different Firebase sites (optional):
      # site_mappings: '{"web-app":"my-project-web","admin-app":"my-project-admin","mobile-app":"my-project-mobile"}'
      # Base branch (optional, defaults to 'main'):
      # base_branch: 'develop'
      # Disable issue commenting (optional, defaults to true):
      # comment_on_issue: false
    secrets:
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
